require celery version to be at least 3.1.18
When using `pip install -r requirements.txt` I was finding that my Celery
worker was not booting properly.

```
...
File "/env/lib/python2.7/site-packages/django/core/management/base.py", line 534, in check
    self.stderr.write(msg, lambda x: x)
TypeError: function takes exactly 1 argument (2 given)
```

This is an incompatibility between Celery 3.1.17 and Django 1.8.
https://github.com/celery/celery/issues/2536

Fix: upgrade to Celery 3.1.18, which supports Django 1.8.
http://docs.celeryproject.org/en/latest/history/changelog-3.1.html#version-3-1-18